### FBI UCR Data

Data downloaded from : [FBI Hate Crime](https://ucr.fbi.gov/hate-crime)

Raw Data Files Present in : raw_data/FBI-UCR

In [1]:
Table8_location = "raw_data/FBI-UCR/Table8/"

In [2]:
!ls -l raw_data/FBI-UCR/Table8/

total 600
-rw-r--r--@ 1 vijaykalmath  staff  30720 Dec 11 19:07 2010.xls
-rw-r--r--@ 1 vijaykalmath  staff  30720 Dec 11 19:04 2011.xls
-rw-r--r--@ 1 vijaykalmath  staff  27136 Dec 11 19:04 2012.xls
-rw-r--r--@ 1 vijaykalmath  staff  27136 Dec 11 19:04 2013.xls
-rw-r--r--@ 1 vijaykalmath  staff  27136 Dec 11 19:04 2014.xls
-rw-r--r--@ 1 vijaykalmath  staff  26624 Dec 11 19:03 2015.xls
-rw-r--r--@ 1 vijaykalmath  staff  27136 Dec 11 19:03 2016.xls
-rw-r--r--@ 1 vijaykalmath  staff  27136 Dec 11 19:03 2017.xls
-rw-r--r--@ 1 vijaykalmath  staff  27136 Dec 11 19:03 2018.xls
-rw-r--r--@ 1 vijaykalmath  staff  39936 Dec 11 19:03 2019.xls

In [3]:
import pandas as pd 
import numpy as np

In [4]:
def ParseExcel(Filename,skiprow_val = 3 ,skipfooter_val = 4):
    return pd.read_excel(Filename,skiprows=skiprow_val,skipfooter = skipfooter_val)

Table8_DF_2010 = ParseExcel(Table8_location + "2010.xls",3,3)
Table8_DF_2010["Year"] = 2010
Table8_DF_2010.rename(columns={'Religious\norganization':'Religious \norganization'},inplace=True)

# Next Year 2011 
Table8_DF_2011 = ParseExcel(Table8_location + "2011.xls",4,3)
Table8_DF_2011["Year"] = 2011 
Table8_DF_2011

# Next Year 2012
Table8_DF_2012 = ParseExcel(Table8_location + "2012.xls",5,3)
Table8_DF_2012["Year"] = 2012 
Table8_DF_2012

# Next Year 2013
Table8_DF_2013 = ParseExcel(Table8_location + "2013.xls",5,3)
Table8_DF_2013["Year"] = 2013 
Table8_DF_2013

# Next Year 2014
Table8_DF_2014 = ParseExcel(Table8_location + "2014.xls",5,3)
Table8_DF_2014["Year"] = 2014 
Table8_DF_2014

# Next Year 2015
Table8_DF_2015 = ParseExcel(Table8_location + "2015.xls",5,3)
Table8_DF_2015["Year"] = 2015 
Table8_DF_2015

# Next Year 2016
Table8_DF_2016 = ParseExcel(Table8_location + "2016.xls",5,3)
Table8_DF_2016["Year"] = 2016 
Table8_DF_2016

# Next Year 2017
Table8_DF_2017 = ParseExcel(Table8_location + "2017.xls",5,3)
Table8_DF_2017["Year"] = 2017
Table8_DF_2017

# Next Year 2018
Table8_DF_2018 = ParseExcel(Table8_location + "2018.xls",5,3)
Table8_DF_2018["Year"] = 2018
Table8_DF_2018

# Next Year 2019
Table8_DF_2019 = ParseExcel(Table8_location + "2019.xls",5,3)
Table8_DF_2019["Year"] = 2019
Table8_DF_2019

,Unnamed: 0,Unnamed: 1,Individual,Business/\nfinancial\ninstitution,Government,Religious \norganization,Society/\npublic1,Other/\nunknown/\nmultiple,Year
0,Total,7314,5524,478,263,208,194,647,2019
1,Single-Bias Incidents,7103,5410,466,240,194,191,602,2019
2,Race/Ethnicity/Ancestry,3963,3269,218,120,12,136,208,2019
3,Religion,1521,701,182,103,170,29,336,2019
4,Sexual Orientation,1195,1068,42,14,12,9,50,2019
5,Disability,157,137,8,1,0,10,1,2019
6,Gender,69,60,2,1,0,3,3,2019
7,Gender Identity,198,175,14,1,0,4,4,2019

In [5]:
Table_list = [
                Table8_DF_2010,
                Table8_DF_2011,
                Table8_DF_2012,
                Table8_DF_2013,
                Table8_DF_2014,
                Table8_DF_2015,
                Table8_DF_2016,
                Table8_DF_2017,
                Table8_DF_2018,
                Table8_DF_2019
            ]

In [6]:
for table in Table_list:
    table.rename(columns={'Unnamed: 0':"Bias motivation", 'Unnamed: 1':"Total incidents"},inplace=True)
#     print(table.columns)
Table8_DF_2010.columns

Index(['Bias motivation', 'Total incidents', 'Individual',
       'Business/\nfinancial\ninstitution', 'Government',
       'Religious \norganization', 'Society/\npublic1',
       'Other/\nunknown/\nmultiple', 'Year'],
      dtype='object')

In [7]:
FBI_UCR_TABLE8_FINALIZED = pd.concat(Table_list)

In [8]:
FBI_UCR_TABLE8_FINALIZED

FBI_UCR_TABLE8_FINALIZED = FBI_UCR_TABLE8_FINALIZED.loc[:,~FBI_UCR_TABLE8_FINALIZED.columns.str.startswith('Unnamed')]

In [9]:
FBI_UCR_TABLE8_FINALIZED.columns

Index(['Bias motivation', 'Total incidents', 'Individual',
       'Business/\nfinancial\ninstitution', 'Government',
       'Religious \norganization', 'Society/\npublic1',
       'Other/\nunknown/\nmultiple', 'Year'],
      dtype='object')

In [10]:
FBI_UCR_TABLE8_FINALIZED.rename(columns=
                                {
                                            "Business/\nfinancial\ninstitution":"Business/FinancialInstitutions",
                                            'Religious\norganization':'ReligiousOrganization',
                                            'Society/\npublic1':'Society Public',
                                            'Other/\nunknown/\nmultiple':"Other",
                                            'Religious \norganization':'ReligiousOrganization'
                                }
                                ,inplace=True)

In [11]:
FBI_UCR_TABLE8_FINALIZED

,Bias motivation,Total incidents,Individual,Business/FinancialInstitutions,Government,ReligiousOrganization,Society Public,Other,Year
0,Total,6628,5236,331,267,188,9,597,2010
1,Single-Bias Incidents,6624,5232,331,267,188,9,597,2010
2,Race,3135,2574,167,162,20,7,205,2010
3,Religion,1322,678,112,74,163,0,295,2010
4,Sexual Orientation,1277,1177,30,18,1,0,51,2010
...,...,...,...,...,...,...,...,...,...
3,Religion,1521,701,182,103,170,29,336,2019
4,Sexual Orientation,1195,1068,42,14,12,9,50,2019
5,Disability,157,137,8,1,0,10,1,2019
6,Gender,69,60,2,1,0,3,3,2019
7,Gender Identity,198,175,14,1,0,4,4,2019

In [12]:
FBI_UCR_TABLE8_FINALIZED.to_csv("processed_data/FBI-UCR/FBI_UCR_TABLE8.csv", index=False)